Finances/Controllers/CategoriesController.cs
using Finances.Models.Entities;
using Finances.Models.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Finances.Controllers
{
    public class CategoriesController : Controller
    {
        CategoriesRepository categoriesRepository = new CategoriesRepository();


        public ActionResult Index()
        {
            if (Session["loggedIn"] == null) return RedirectToAction("Login","Home");


            return View(categoriesRepository.GetAllFromUser((int)Session["id_user"]));
        }

        [HttpGet]
        public ActionResult New()
        {
            if (Session["loggedIn"] == null) return RedirectToAction("Login","Home");

            else return View();
        }

        [HttpPost]
        public ActionResult New(Category category)
        {
            if (Session["loggedIn"] == null) return RedirectToAction("Login","Home");

            category.id_user = (int)Session["id_user"];
            categoriesRepository.Create(category);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            if (Session["loggedIn"] == null) return RedirectToAction("Login","Home");

            if (categoriesRepository.GetById(id).id_user == (int)Session["id_user"])
            {
                try
                {
                    categoriesRepository.Delete(id);
                }catch(MySql.Data.MySqlClient.MySqlException ex)
                {
                    TempData["error"]= "Não é possível excluir uma categoria que possui depesas catadastradas.";
                }
            }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Category category = categoriesRepository.GetById(id);

            if (category.id_user == (int)Session["id_user"])
            {
                return View(category);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public ActionResult Edit(Category category)
        {
            if (category.id_user == (int)Session["id_user"])
            {
                categoriesRepository.Edit(category);
            }

            return RedirectToAction("Index");

        }
    }
}

Finances/Controllers/EstablishmentsController.cs
using Finances.Models.Entities;
using Finances.Models.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Finances.Controllers
{
    public class EstablishmentsController : Controller
    {
        
        EstablishmentsRepository establishmentsRepository = new EstablishmentsRepository();


        public ActionResult Index()
        {
            if (Session["loggedIn"] == null) return RedirectToAction("Login","Home");

         
            return View(establishmentsRepository.GetAllFromUser((int)Session["id_user"]));
        }

        [HttpGet]
        public ActionResult New()
        {
            if (Session["loggedIn"] == null) return RedirectToAction("Login","Home");
            
            else return View();
        }

        [HttpPost]
        public ActionResult New(Establishment establishment)
        {
            if (Session["loggedIn"] == null) return RedirectToAction("Login","Home");

            establishment.id_user = (int)Session["id_user"];
            establishmentsRepository.Create(establishment);
            return RedirectToAction("Index");
        }

        public ActionResult Delete(int id)
        {
            if (Session["loggedIn"] == null) return RedirectToAction("Login","Home");

            if (establishmentsRepository.GetById(id).id_user == (int)Session["id_user"])
            {
                try
                {
                    establishmentsRepository.Delete(id);
                }catch (MySql.Data.MySqlClient.MySqlException ex)
                {
                    TempData["error"] = "Não é possível excluir um estabelecimento que possui depesas cadastradas.";
                }
        }
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            Establishment establishment = establishmentsRepository.GetById(id);

            if (establishment.id_user == (int)Session["id_user"])
            {
                return View(establishment);
            }
            else
            {
                return RedirectToAction("Index");
            }
        }

        [HttpPost]
        public ActionResult Edit(Establishment establishment)
        {
            if (establishment.id_user == (int)Session["id_user"])
            {
                establishmentsRepository.Edit(establishment);
            }

            return RedirectToAction("Index");

        }
    }
}

Finances/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Finanças", "Index", "Expenses", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse ">
                <ul class="nav navbar-nav  navbar-right">
                    @if (!(Session["loggedIn"] != null))
                    {
                        <li>@Html.ActionLink("Login", "Login", "Home")</li>
                        <li>@Html.ActionLink("Registrar-se", "Register", "Home")</li>
                    }
                    else
                    {

                        <li>@Html.ActionLink("Despesas", "Index", "Expenses")</li>
                        <li>@Html.ActionLink("Categorias", "Index", "Categories")</li>
                        <li>@Html.ActionLink("Estabelecimentos", "Index", "Establishments")</li>
                        <li>@Html.ActionLink("Sair", "Logout", "Home")</li>

                    }
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>Desenvolvido por <a href="http://www.github.com/heitor-gia">Heitor Gianastasio</a></p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>